### ISSUE TITLE
specify license

### ISSUE THREAD

**Issue by mtmail** [hajmolafury/mysqldump-to-csv#2]
Can you add the license to this project?

**Comment by mtmail** [comment]
If I'm not mistaken this repository is a copy of https://github.com/jamesmishra/mysqldump-to-csv The license should be "MIT License (MIT), Copyright (c) 2014 James Mishra" then.

**Comment by abubelinha** [comment]
I agree with @mtmail , looks like @jamesmishra should be mentioned
